### ISSUE TITLE
new important issues

### ISSUE THREAD

**Issue by JecobYau** [zkhssb/NectarRCON#2]
Hello developer, I have a new requirement, I have already given you a star, I need rcon to send the same command to all servers at the same time, so every time I send an rcon command, I need to reconnect to a new rcon, which is very troublesome, so can you add a multi-rcon server connection function? The same command is executed by multiple rcon nodes at the same time, which will make the efficiency much faster. Of course, I can also use your code to continue development, but because I am the server administrator, I may not have that much time. So I hope you can add this function. Thank you very much for your contribution!

**Comment by zkhssb** [comment]
Hello, thank you for your new requirement and the star you gave me. I understand that you need a multi-rcon server connection function to send the same command to all servers simultaneously, which would significantly improve efficiency. I can certainly add this functionality to the project for you.

However, I want to inform you that I currently have limited availability and may not have much free time to work on it immediately. Therefore, it might take some time for me to implement the multi-rcon server connection function. I apologize for any inconvenience caused by this delay. Rest assured, I will do my best to support your request as soon as possible.

Thank you for your understanding and patience.

**Comment by JecobYau** [comment]
I’m grateful for your response, and it’s fine if you have other priorities. You have made this project awesome, and I’m waiting for your feedback when you are available. Live happily.

**Comment by zkhssb** [comment]
The feature has been added to [v1.0.0-beta3](https://github.com/zkhssb/NectarRCON/releases/tag/v1.0.0-beta3)! ^3^
