### ISSUE TITLE
some bug

### ISSUE THREAD

**Issue by JecobYau** [zkhssb/NectarRCON#5]
I encountered a problem, every time I execute a command, it shows: Keep Alive Keep Alive Keep Alive first, and then there is no return data until the next command is executed, then it shows the return result of the previous command, and so on. By the way, can NectarRCON support Unicode characters?

**Comment by zkhssb** [comment]
Hi JecobYau
Thank you for your feedback. In order to better understand the issue you encountered, could you please provide some screenshots? Although I understand what "Keep Alive" means, I'm not clear about its specific cause in your case. Regarding the support for Unicode characters in NectarRCON, it should be possible as WPF generally supports Unicode characters. However, there might be certain Unicode characters that cannot be displayed correctly.

**Comment by zkhssb** [comment]
If you haven't cleared the logs, you can find the log files in the "./logs" directory in the root directory of the program.

**Comment by JecobYau** [comment]
[image: image.png]

MiuxuE ***@***.***> 于2023年9月5日周二 18:01写道：

**Comment by JecobYau** [comment]
![image](https://github.com/zkhssb/NectarRCON/assets/53740262/8cef6d9f-aa71-46a4-98d3-a2610809959f)

**Comment by zkhssb** [comment]
This seems to be a command result from the server, but it could also be a Socket exception message. Currently, I am not sure about the cause of this problem. Additionally, do you know the core and game version used by this server? Can you provide this information?

**Comment by zkhssb** [comment]
Hello, do you still encounter this problem?
